//
// GameboardAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class GameboardAPI: APIBase {
    
        /**
         
         Retrieve a list of Genres
         
         - GET /genres
         - The top level cateogiresation of Gameboard so a user can navigate through the Genres, Categories and Games, and then finally to Boards
         - examples: [{contentType=application/json, example=[ {
  "gid" : "",
  "subTitle" : "aeiou",
  "endDate" : "aeiou",
  "imageUrl" : "aeiou",
  "count" : "",
  "title" : "aeiou"
} ]}]

         - returns: RequestBuilder<[Genre]> 
         */
        public class func genresGet() -> RequestBuilder<[Genre]> {
            let path = "/genres"
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [:]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<[Genre]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
