//
// Genre.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Genre: JSONEncodable {

    /** Unique Genre ID */
    public var gid: Int?
    /** Image URL to be displayed. */
    public var imageUrl: String?
    /** Display name of the Genre. */
    public var title: String?
    /** Capacity of product. For example, 4 people. */
    public var subTitle: String?
    /** Number of Categories within the Genres */
    public var count: Int?
    /** Date the Genre operates from */
    public var endDate: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["gid"] = self.gid
        nillableDictionary["imageUrl"] = self.imageUrl
        nillableDictionary["title"] = self.title
        nillableDictionary["subTitle"] = self.subTitle
        nillableDictionary["count"] = self.count
        nillableDictionary["endDate"] = self.endDate
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
